const nationalities = [
  'Afghanistan',
  'Afrika Selatan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua dan Barbuda',
  'Arab Saudi',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belanda',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia dan Herzegovina',
  'Botswana',
  'Brasil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Chad',
  'Chile',
  'China',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Republik Dominika',
  'Ekuador',
  'El Salvador',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Filipina',
  'Finlandia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Ghana',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungaria',
  'India',
  'Indonesia',
  'Inggris',
  'Irak',
  'Iran',
  'Irlandia',
  'Islandia',
  'Israel',
  'Italia',
  'Jamaika',
  'Jepang',
  'Yaman',
  'Yordania',
  'Kamboja',
  'Kamerun',
  'Kanada',
  'Kazakhstan',
  'Kenya',
  'Kepulauan Marshall',
  'Kirgistan',
  'Kiribati',
  'Kolombia',
  'Komoro',
  'Kongo',
  'Korea Selatan',
  'Korea Utara',
  'Kosta Rika',
  'Kroasia',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lesotho',
  'Libanon',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lituania',
  'Luksemburg',
  'Makedonia Utara',
  'Madagaskar',
  'Maladewa',
  'Malawi',
  'Malaysia',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Meksiko',
  'Mesir',
  'Mikronesia',
  'Moldova',
  'Monako',
  'Mongolia',
  'Montenegro',
  'Moroko',
  'Mozambik',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Nigeria',
  'Nikaragua',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestina',
  'Panama',
  'Papua Nugini',
  'Paraguay',
  'Peru',
  'Polandia',
  'Portugal',
  'Prancis',
  'Qatar',
  'Republik Afrika Tengah',
  'Republik Ceko',
  'Republik Dominika',
  'Rumania',
  'Rusia',
  'Rwanda',
  'Saint Kitts dan Nevis',
  'Saint Lucia',
  'Saint Vincent dan Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome dan Principe',
  'Selandia Baru',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapura',
  'Siprus',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'Spanyol',
  'Sri Lanka',
  'Sudan',
  'Sudan Selatan',
  'Suriah',
  'Suriname',
  'Swedia',
  'Swiss',
  'Tajikistan',
  'Tanzania',
  'Timor-Leste',
  'Tiongkok',
  'Togo',
  'Tonga',
  'Trinidad dan Tobago',
  'Tunisia',
  'Turki',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraina',
  'Uni Emirat Arab',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatikan',
  'Venezuela',
  'Vietnam',
  'Yunani',
  'Zambia',
  'Zimbabwe'
]

module.exports = nationalities
